In [2]:
import pandas as pd
import numpy as np

In [4]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "irrigation_prediction.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [5]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 10000
Columns : 20

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  str
 14  Water_Source             10000 non-null  str
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  str
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  str
 19  Irrigation_Need          10000 non-null  str
dtypes: float64(11), str(9)
memory usage: 2.0 MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Soil_pH,10000.0,6.487857,0.979963,4.80,5.640,6.470,7.3500,8.20
Soil_Moisture,10000.0,36.969207,16.430845,8.00,22.860,37.240,50.9400,65.00
Organic_Carbon,10000.0,0.944731,0.372406,0.30,0.620,0.950,1.2600,1.60
Electrical_Conductivity,10000.0,1.791963,0.984202,0.10,0.940,1.780,2.6500,3.50
Temperature_C,10000.0,26.991423,8.664074,12.00,19.460,27.090,34.5000,42.00
Humidity,10000.0,60.080339,20.187973,25.00,42.855,60.040,77.7050,95.00
Rainfall_mm,10000.0,1252.499420,715.582201,0.38,634.155,1250.335,1880.2650,2499.69
Sunlight_Hours,10000.0,7.518538,2.016077,4.00,5.760,7.560,9.2600,11.00
Wind_Speed_kmh,10000.0,10.163545,5.670923,0.50,5.160,10.190,15.1000,20.00
Field_Area_hectare,10000.0,7.598024,4.233919,0.30,3.950,7.540,11.2025,15.00
Previous_Irrigation_mm,10000.0,59.864122,34.483722,0.02,30.160,59.630,90.0300,119.99

In [9]:
df.isnull().sum()
df.isnull().sum().sort_values(ascending=False)

Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
Irrigation_Need            0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [12]:
df["Irrigation_Need"].value_counts()
df["Irrigation_Need"].value_counts(normalize=True) * 100

Irrigation_Need
Low       58.64
Medium    38.00
High       3.36
Name: proportion, dtype: float64

In [13]:
categorical_features = df.select_dtypes(include="object").columns.tolist()

numerical_features = df.select_dtypes(exclude="object").columns.tolist()

print("Categorical Features")
print(categorical_features)

print()

print("Numerical Features")
print(numerical_features)

Categorical Features
['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season', 'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region', 'Irrigation_Need']

Numerical Features
['Soil_pH', 'Soil_Moisture', 'Organic_Carbon', 'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm', 'Sunlight_Hours', 'Wind_Speed_kmh', 'Field_Area_hectare', 'Previous_Irrigation_mm']

C:\Users\nudas\AppData\Local\Temp\ipykernel_20072\2424154350.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(include="object").columns.tolist()

## Initial Observations

- Dataset contains ______ rows and ______ columns.
- There are ______ numerical features.
- There are ______ categorical features.
- Missing values: ______.
- Duplicate rows: ______.
- Target variable: Irrigation_Need.
- The classes appear to be balanced / imbalanced.
- The dataset is suitable for a multiclass classification problem.